### ISSUE TITLE
How to Fix this issue ?

### ISSUE THREAD

**Issue by MooonShot** [GetLightBite/StriveSDK_iOS#1]
Hello I was trying to build the demo app, I did everything that's in the tutorial but When I build the app it show this error, How to fix this ?

Thanks
![screen shot 2017-07-29 at 12 36 33 am](https://user-images.githubusercontent.com/20306382/28732640-336bc91c-73f6-11e7-834a-6c61bf2fb16d.png)

**Comment by sebleon** [comment]
Ah just saw this, my apologies - could you show me what it says in the error logs [1]

Could you double check that you followed the steps around setting up Strive in AppDelegate? Haven't run into this issue before, but happy to help!

[1] do this by right clicking the error message (the one highlighted in blue), and hit `Reveal in Log`
